### ISSUE TITLE
Explicit transaction management

### ISSUE THREAD

**Issue by elfring** [mmottl/postgresql-ocaml#14]
It can happen that I want to [make changes to database contents](https://en.wikipedia.org/wiki/Database_transaction "Description for database transactions") more often permanent before the corresponding SQL statement or connection handle will be closed. Thus I am looking for [ways to control a commit strategy](https://en.wikipedia.org/wiki/Commit_%28data_management%29 "Committing your data").

I would also appreciate if [a database rollback](https://en.wikipedia.org/wiki/Rollback_%28data_management%29 "Description for database rollback") can be triggered explicitly when a special condition was detected by dedicated program logic.

**Comment by mmottl** [comment]
It should already be possible to use all SQL features, including transactions (begin transaction, commit, rollback, etc).  Just e.g. send a "begin transaction" command to the database before executing other statements.  If something goes wrong during the execution of your program, you can just send "rollback".
