### ISSUE TITLE
Lwt layer

### ISSUE THREAD

**Issue by fxfactorial** [mmottl/postgresql-ocaml#19]
Is it possible to add an Lwt/non blocking layer? I mean for this library to provide it.

**Comment by mmottl** [comment]
I'd make this a separate package.  There are many choices for non-blocking frameworks.  There is no good reason to bake any specific one into these OCaml bindings.

**Comment by fxfactorial** [comment]
@mmottl I meant more like `postgresql.lwt`, `postgresql.async`. If the lib came with something like that then usage of these bindings would be easier, surely that's a good reason? 

In any case, thanks for the great code.

**Comment by mmottl** [comment]
I guess you mean for the specification of findlib packages?  If sub-packages can be specified from within separate distributions (not sure whether or how that would work), then I'd be fine with that.  But I don't think that Lwt-packages, etc., should become part of the distribution of the basic bindings.  Nor should Postgresql-support go into the Lwt-distribution.  That would introduce too many dependencies.  Keeping things as atomic as possible seems like good packaging practice.

**Comment by fxfactorial** [comment]
@mmottl okay thanks for your time, I will have to look to pgocaml for my needs then.
