### ISSUE TITLE
Support binary results

### ISSUE THREAD

**Issue by pbiggar** [mmottl/postgresql-ocaml#26]
We're storing large binary data in our DB. We saw a 3x speedup when inserting the data using binary format, vs using escaped text.

However, I don't see a way to get binary data out of postgres without escaping it. I believe that is due to [this line](https://github.com/mmottl/postgresql-ocaml/blob/10f513c0073f19ce961105ea2619ee6f158ad1ac/src/postgresql_stubs.c#L643), in which the resultFormat is 0 (indicating text) with no way of setting it to 1.

Does this seem right? Can we add a way of setting it to 1 to get output as binary?

**Comment by mmottl** [comment]
Please feel free to add support for changing the output format to the mentioned function.  The default should, of course, be text so as not to break existing code.  I'll gladly merge your changes.

**Comment by pbiggar** [comment]
My thinking is:
- add an extra boolean argument `return_binary` to PQexecParams_stub
- add an extra optional boolean argument, `return_binary` (default false) to exec_params

Sound good? I can code that up in the next few weeks if so.

**Comment by mmottl** [comment]
Thanks, sounds fine with me!
