### ISSUE TITLE
Broken API-documentation link in README.md

### ISSUE THREAD

**Issue by joelonsql** [mmottl/postgresql-ocaml#29]
The link by clicking "online" in "The API-documentation can also be found online"
goes to http://mmottl.github.io/postgresql-ocaml/api/postgresql
which doesn't work.

Where can the API-documentation be found?

**Comment by abhi18av** [comment]
Still not resolved as of now :)

**Comment by mmottl** [comment]
Patience, there are still some problems with the latest Dune release tool.  Once that's fixed, I'll make a new release, including the API documentation.

**Comment by abhi18av** [comment]
Thanks @mmottl  :)

**Comment by mmottl** [comment]
Still no updates, the issue seems to be alive and well in `dune-release`:

https://github.com/samoht/dune-release/issues/117
https://github.com/samoht/dune-release/issues/114

**Comment by dbuenzli** [comment]
It seems they are trying to create temporary files in directories which do not exist. You could try to do a `mkdir doc && mkdir api` before and it suspect it will work.

**Comment by dbuenzli** [comment]
and if they kept the `topkg` workflows, you don't have to publish a release to publish the doc, a `dune-release distrib && dune-release publish doc` should do.

**Comment by mmottl** [comment]
Thanks, I was aware of the `dune-release distrib && dune-release publish doc` shortcut.  But I'm not sure what to do about the error.  The command will check out a fresh `gh-pages` branch and then apparently delete its `api` directory without recreating it.

**Comment by mmottl** [comment]
I've fixed this issue with a patched version of `dune-release`: https://github.com/samoht/dune-release/pull/136

I hope the patched `dune-release` will soon become publicly available.
