### ISSUE TITLE
return-type for prepared statements appear to be hardcoded to the "text" format

### ISSUE THREAD

**Issue by TyOverby** [mmottl/postgresql-ocaml#45]
[PQexecParams_stub](https://github.com/mmottl/postgresql-ocaml/blob/master/src/postgresql_stubs.c#L643) takes a `v_binary_result` argument, which tells postgres to use the text or binary format.

[PQexecPrepared](https://www.postgresql.org/docs/9.1/libpq-exec.html) has the same argument, [but the value is hardcoded to "text"](https://github.com/mmottl/postgresql-ocaml/blob/master/src/postgresql_stubs.c#L727).

@mmottl: would you be opposed to me adding this functionality to postgresql-ocaml, and if not, do you foresee any issues that I may run into?

**Comment by mmottl** [comment]
Sorry for the long delay, please feel free to prepare a PR. The code has been significantly reformatted.
