### ISSUE TITLE
Wrong clause number in LGPL special exception

### ISSUE THREAD

**Issue by flux77** [mmottl/postgresql-ocaml#47]
The special exception part of the license file says:

>By "a publicly distributed version of the Library", we mean either the unmodified Library as distributed by the authors, or a modified version of the Library that is distributed under the conditions defined in clause 3 of the GNU Lesser General Public License.

It should be "clause 2", not "clause 3".

This is the same typo made in OCaml's license: https://github.com/ocaml/ocaml/commit/2d26308ad4d34ea0c00e44db62c4c24c7031c78c

**Comment by mmottl** [comment]
Thanks for pointing this out, I've fixed the license clause in all my packages.
