### ISSUE TITLE
res#getvalue couldn't get value without `for-to` iteration

### ISSUE THREAD

**Issue by liweijian** [mmottl/postgresql-ocaml#7]
I want to `select` one data from database, the following code print nothing:

```ocaml
let insert_ua ua =
  let conn = connect () in
  let s_q = "select log_id from devices where ua='' limit 1" in
  conn#send_query s_q;
  match conn#get_result with
  | Some res -> begin 
                  match res#status with
                  | Tuples_ok ->
                      printf "%d-%d-%s, " 0  0 (res#getvalue 0 0)
                  | _ -> printf "wtf\n";
                end
  | None -> ()
```

However, the following prints the data I need: `0-0-9,`.

```ocaml
let insert_ua ua =
  let conn = connect () in
  let s_q = "select log_id from devices where ua='' limit 1" in
  conn#send_query s_q;
  match conn#get_result with
  | Some res -> begin 
                  match res#status with
                  | Tuples_ok ->
                      for tuple = 0 to res#ntuples - 1 do
                        for field = 0 to res#nfields - 1  do
                          printf "%d-%d-%s, " tuple field (res#getvalue tuple field)
                        done;
                        print_newline ()
                      done
                  | _ -> printf "wtf\n";
                end
  | None -> ()
```

I don't know what's the difference between these two functions, since the `tuple` and `field` are both `0` in my case.

**Comment by mmottl** [comment]
Funny, I was just about to look into this.  In case you found out what the problem was, it would be helpful to quickly describe the resolution in case others run into a similar issue.

**Comment by liweijian** [comment]
I just added a `;` after the `printf "%d-%d-%s, " 0  0 (res#getvalue 0 0)`, and it works.

@mmottl thanks for your reply:)

**Comment by mmottl** [comment]
@liweijian Hm, the semicolon shouldn't matter.  I suspect your problem was that you hadn't flushed the output channel.  Note that the `print_newline` in the second (working) example not only prints a newline, it will also flush `stdout`.  `printf` alone will not do that unless you put a flush operator `%!` into the format string, or unless the output buffer is full.

**Comment by liweijian** [comment]
Thanks, I'm now trying to port my VPS's services from Racket&MySQL to OCaml&PostgreSQL.

I got an error `mainsvr.native: main: ("Postgresql.Error(_)")`.

I've view the postgresql's log

```
 /tmp> cat postgresql-2015-02-17_163629.log
LOG:  00000: database system was shut down at 2015-02-17 11:19:42 CST
LOCATION:  StartupXLOG, xlog.c:6011
LOG:  00000: database system is ready to accept connections
LOCATION:  reaper, postmaster.c:2630
LOG:  00000: autovacuum launcher started
LOCATION:  AutoVacLauncherMain, autovacuum.c:425
LOG:  00000: statement: insert into devices (model,sdkv,firm,ua,manufacturer) values ('',1,'','','')
LOCATION:  exec_simple_query, postgres.c:887
LOG:  00000: statement: select log_id from devices where ua='' limit 1
LOCATION:  exec_simple_query, postgres.c:887
```

I can't find the point, the code is

```ocaml
let insert_ua ua =
  let conn = connect () in
  conn#send_query
           "insert into devices (model,sdkv,firm,ua,manufacturer) values ('',1,'','','')";
  assert ((fetch_single_result conn)#status = Command_ok);
  printf "before select log_id###\n";
  let s_q = "select log_id from devices where ua='' limit 1" in
  conn#send_query s_q;
  printf "After send_query###\n";
  let log_id =
    match conn#get_result with
    | Some res -> begin 
                    match res#status with
                    | Tuples_ok ->
                        res#getvalue 0 0
                    | _ -> "-1"
                  end
    | None -> "-2"
  in
    printf "logid:%s\n" log_id;
    conn#send_prepare "update_ua"
                      "UPDATE devices SET ua='$1' WHERE log_id=$2";
    assert ((fetch_single_result conn)#status = Command_ok);
    conn#send_query_prepared ~params:[|ua ; log_id|] "update_ua";
    assert ((fetch_single_result conn)#status = Command_ok);
    log_id
```

The logic is simple, I just `insert` a record in database, `select` the first record I need to update, then `update` it.

I tried to add several `printf` in the function in order to find where bug is, but there's nothing to print.

**Comment by mmottl** [comment]
Always place the flush operator `%!` at the end of printf debug statements to make sure you get all output right away.  If output doesn't appear, maybe the application is blocking while waiting for a reply.

This programming problem may be too generic for an issue report on GitHub, since there is no indication that the library bindings are failing.
